### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [senaig97/Project#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by ghost** [comment]
hoi

**Comment by senaig97** [comment]
hello

**Comment by walton-ma** [comment]
Hello there

**Comment by ProfRojas** [comment]
Please have all of your teammates respond. Otherwise, you will only receive partial credit for the GitHub portion. I also need to know your group number and class section.

**Comment by ayushshrivastava123** [comment]
Hello. The class section is MoWe 4:30-5:45 and we are team 2.

**Comment by ProfRojas** [comment]
Thanks!
